#
# Global configuration
#

encoding: utf-8
timezone: Europe/Moscow



#
# Serve command options
#

host: 0.0.0.0



#
# @see http://jekyllrb.com/docs/assets/
#
sass:
    sass_dir: _assets/scss
    style: compressed



#
# GitHub defaults
#
kramdown:
    input: GFM
    hard_wrap: false

gems:
    - jekyll-coffeescript
    - jekyll-paginate

lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
    noscript: false
